wordListEasy = [
    "apple", "bread", "dance", "eagle", "funny", "great", "happy", "ideal", "jelly",
    "knife", "lemon", "magic", "night", "ocean", "piano", "queen", "river", "storm",
    "tiger", "under", "value", "water", "zebra", "above", "brave", "chair", "dream",
    "earth", "fable", "giant", "house", "image", "jewel", "light", "money", "novel",
    "onion", "peace", "quiet", "rainy", "smart", "train", "unity", "voice", "white",
    "young", "actor", "bravo", "cloud", "drink", "extra", "flash", "green", "heart",
    "input", "judge", "kites", "logic", "metal", "nurse", "other", "paint", "quick",
    "robot", "score", "thumb", "visit", "world", "badge", "cabin", "drove", "entry",
    "frost", "horse", "inbox", "large", "minor", "order", "prize", "rules", "share",
    "trust", "vault", "wired", "badge", "clear", "dance", "eagle", "fence", "glove",
    "ideal", "jolly", "leave", "north", "pilot", "quest", "roost", "sleep", "taste",
    "valid", "waste", "amber", "batch", "clown", "drive", "flute", "joint", "mirth",
    "other", "shark", "uncle", "yearn", "blaze", "field", "inbox", "judge", "lemons",
    "metal", "north", "raise", "shine", "unite", "special", "xylem", "block", "entry",
    "giant", "happy", "leave", "magic", "novel", "social", "pilot", "quest", "robot",
    "storm", "voice", "waste", "yearn", "zebra", "silos"
]


wordListMedium = [
    "arctic", "bakery", "bottle", "castle", "danger", "elastic", "friend", "glimpse",
    "harvest", "impact", "journey", "kingdom", "lantern", "medical", "necklace",
    "office", "puzzle", "quench", "remark", "scholar", "travel", "uniform", "vintage",
    "writer", "athlete", "banish", "cactus", "device", "eagerly", "future", "grateful",
    "honest", "insure", "jungle", "kitten", "locket", "marvel", "nature", "orange",
    "patient", "quietly", "rescue", "summit", "tackle", "unique", "vanity", "wander",
    "abduct", "cereal", "delight", "envelope", "flourish", "gravy", "health", "inspire",
    "jigsaw", "kindred", "luminous", "mature", "notable", "outcome", "parable", "quiver",
    "raccoon", "student", "twilight", "uncover", "virtue", "wistful", "abandon", "cavity",
    "density", "elastic", "flannel", "gossip", "humble", "intact", "jeopardy", "kneecap",
    "lantern", "marvel", "nomadic", "observe", "pendant", "quirky", "reliable", "sphinx",
    "tailor", "umbrella", "verify", "watered", "absolve", "beliefs", "chisel", "demand",
    "eternal", "famine", "grapple", "helix", "imitate", "jumbled", "kitten", "lizard",
    "migrate", "notepad", "oppose", "prism", "quicks", "riddle", "tether", "upgrade",
    "vibrant", "waffle", "abduct", "baggage", "compete", "destiny", "emulate", "foreman",
    "grasping", "handful", "insulin", "junction", "kidnap", "lattice", "mandate",
    "navigated", "operator", "plastic", "quests", "resource", "shrink", "theorem",
    "unstable", "vantage", "warlock", "abandon", "breezy", "crucial", "dazzle",
    "educate", "follow", "galaxy", "hurdle", "iceberg", "jumbled", "keeper", "launch",
    "muffled", "nobody", "optics", "parade", "quizzed", "reluct", "soaring", "twilight",
    "unravel", "victory", "wildlife", "x-rays", "yearlong", "zephyr", "abrupt", "buffet",
    "capital", "delight", "exploit", "flicker", "graphic", "hospital", "inherit",
    "jeopardy", "kneeling", "lantern", "marvel", "nurture", "operate", "pulsate",
    "quench", "report", "stumble", "trigger", "urgent", "vintage", "whistle", "xylose",
    "yonder", "zealot", "abound", "bracket", "counsel", "doubled", "escort", "fracture",
    "gather", "hectare", "involve", "journal", "kinship", "believe", "circuit", "freedom",
    "generate", "happiness", "improve", "journey", "keystone", "loyalty", "miracle",
    "notices", "obtain", "precise", "quieter", "remnant", "serious", "trouble", "utopia"
]

wordListDifficult = [
    "abandon", "abduct", "abyssal", "banish", "blight", "brutal", "cadence", "casket",
    "chilly", "chaos", "cinder", "clumsy", "concur", "cosmic", "crypts", "decade",
    "deluge", "dismal", "distort", "docket", "droned", "dwindle", "elation", "embark",
    "enigma", "erupt", "exotic", "failure", "famine", "feeble", "frenzy", "frugal",
    "fumble", "gloomy", "grudge", "grumpy", "haphazard", "haughty", "helix",
    "hesitant", "hopeless", "imminent", "impasse", "incisor", "indulge", "inertia",
    "intrude", "intense", "ironic", "isolate", "jarring", "jigsaw", "jumbled", "kettle",
    "lament", "lethargic", "lofty", "lunacy", "malice", "menace", "migrate", "morose",
    "mumble", "negate", "niche", "nimble", "obscure", "obtain", "oppose", "outcast",
    "overlap", "paradox", "plight", "prism", "prodigy", "quench", "quirky", "racket",
    "relish", "revoke", "rifted", "robust", "sadness", "seismic", "silken", "slump",
    "smudge", "soften", "spunky", "stifle", "surreal", "tactic", "tangle", "taper",
    "tempest", "thwart", "trudge", "uplift", "vagabond", "vexing", "waffle", "witty",
    "wreck", "yearn", "zealot", "abstruse", "afflict", "antagonist", "ascetic",
    "avalanche", "bluster", "budding", "cascade", "coalesce", "corrode", "crucible",
    "curfew", "drifting", "enfold", "ensnare", "evasive", "foliage", "fumbling",
    "garment", "glaring", "grieving", "grizzle", "harmonize", "hefty", "ignoble",
    "illustrate", "imbibe", "intricacy", "juggling", "lament", "mysterious", "neglect",
    "nostalgic", "oblivion", "omnivore", "overcome", "parent", "parity", "penchant",
    "pervade", "quarantine", "quibble", "raucous", "reclaim", "refrain", "scathe",
    "serene", "stifle", "surge", "tempting", "unravel", "unsettle", "vagrant",
    "wistful", "xenophobic", "yearning", "zealousness", "abnormal", "allegory",
    "altruism", "antidote", "arbitrary", "backlash", "bewilder", "blueprint",
    "chortle", "commence", "diverge", "driftwood", "elaborate", "epidemic", "fiasco",
    "fracture", "fortitude", "habitual", "intangible", "jabber", "kinship", "morality",
    "perception", "prolific", "prowess", "quixotic", "reluctant", "sanguine",
    "subtlety", "tumult", "unify", "violate", "wistful", "woven", "yawning",
    "zealot", "zesty", "dwindle"
]


wordListVeryDifficult = [
    'abruptly',
    'absurd',
    'abyss',
    'affix',
    'askew',
    'avenue',
    'awkward',
    'axiom',
    'azure',
    'bagpipes',
    'bandwagon',
    'banjo',
    'bayou',
    'beekeeper',
    'bikini',
    'blitz',
    'blizzard',
    'boggle',
    'bookworm',
    'boxcar',
    'boxful',
    'buckaroo',
    'buffalo',
    'buffoon',
    'buxom',
    'buzzard',
    'buzzing',
    'buzzwords',
    'caliph',
    'cobweb',
    'cockiness',
    'croquet',
    'crypt',
    'curacao',
    'cycle',
    'daiquiri',
    'dirndl',
    'disavow',
    'dizzying',
    'duplex',
    'dwarves',
    'embezzle',
    'equip',
    'espionage',
    'euouae',
    'exodus',
    'faking',
    'fishhook',
    'fixable',
    'fjord',
    'flapjack',
    'flopping',
    'fluffiness',
    'flyby',
    'foxglove',
    'frazzled',
    'frizzled',
    'fuchsia',
    'funny',
    'gabby',
    'galaxy',
    'galvanize',
    'gazebo',
    'giaour',
    'gizmo',
    'glowworm',
    'glyph',
    'gnarly',
    'gnostic',
    'gossip',
    'grogginess',
    'haiku',
    'haphazard',
    'hyphen',
    'iatrogenic',
    'icebox',
    'injury',
    'ivory',
    'ivy',
    'jackpot',
    'jaundice',
    'jawbreaker',
    'jaywalk',
    'jazziest',
    'jazzy',
    'jelly',
    'jigsaw',
    'jinx',
    'jiujitsu',
    'jockey',
    'jogging',
    'joking',
    'jovial',
    'joyful',
    'juicy',
    'jukebox',
    'jumbo',
    'kayak',
    'kazoo',
    'keyhole',
    'khaki',
    'kilobyte',
    'kiosk',
    'kitsch',
    'kiwifruit',
    'klutz',
    'knapsack',
    'larynx',
    'lengths',
    'lucky',
    'luxury',
    'lymph',
    'marquis',
    'matrix',
    'megahertz',
    'microwave',
    'mnemonic',
    'mystify',
    'naphtha',
    'nightclub',
    'nowadays',
    'numbskull',
    'nymph',
    'onyx',
    'ovary',
    'oxidize',
    'oxygen',
    'pajama',
    'peekaboo',
    'phlegm',
    'pixel',
    'pizazz',
    'pneumonia',
    'polka',
    'pshaw',
    'psyche',
    'puppy',
    'puzzling',
    'quartz',
    'queue',
    'quips',
    'quixotic',
    'quiz',
    'quizzes',
    'quorum',
    'razzmatazz',
    'rhubarb',
    'rhythm',
    'rickshaw',
    'schnapps',
    'scratch',
    'shiv',
    'snazzy',
    'sphinx',
    'spritz',
    'squawk',
    'staff',
    'strength',
    'strengths',
    'stretch',
    'stronghold',
    'stymied',
    'subway',
    'swivel',
    'syndrome',
    'thriftless',
    'thumbscrew',
    'topaz',
    'transcript',
    'transgress',
    'transplant',
    'triphthong',
    'twelfth',
    'twelfths',
    'unknown',
    'unworthy',
    'unzip',
    'uptown',
    'vaporize',
    'vixen',
    'vodka',
    'voodoo',
    'vortex',
    'voyeurism',
    'walkway',
    'waltz',
    'wave',
    'wavy',
    'waxy',
    'wellspring',
    'wheezy',
    'whiskey',
    'whizzing',
    'whomever',
    'wimpy',
    'witchcraft',
    'wizard',
    'woozy',
    'wristwatch',
    'wyvern',
    'xylophone',
    'yachtsman',
    'yippee',
    'yoked',
    'youthful',
    'yummy',
    'zephyr',
    'zigzag',
    'zigzagging',
    'zilch',
    'zipper',
    'zodiac',
    'zombie',
]
